name: basket_app
description: Basket app
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.3
  dartz: ^0.9.1
  http: ^0.12.2
  data_connection_checker: ^0.3.4
  shared_preferences: ^0.5.8
  flutter_bloc: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  bloc_test: ^7.0.0

flutter:
  uses-material-design: true
